# Generated by Django 3.2.4 on 2021-06-03 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.BigIntegerField(default=0)),
                ('postal_code', models.BigIntegerField(default=0)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.BigIntegerField(default=0)),
                ('postal_code', models.BigIntegerField(default=0)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipper.sender')),
            ],
        ),
    ]
