# Generated by Django 3.2.4 on 2021-06-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shipper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageId', models.IntegerField(default=3366)),
                ('package_name', models.CharField(max_length=500)),
                ('weight', models.IntegerField(default=0)),
                ('tracking_code', models.CharField(default='DESTI-41483310432338994696', max_length=25)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Shipper.receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipper.sender')),
            ],
        ),
    ]
