# Generated by Django 3.2.4 on 2021-06-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipper', '0002_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='email',
        ),
        migrations.AddField(
            model_name='package',
            name='carrier',
            field=models.CharField(default='DHL', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='carrier_reference_no',
            field=models.CharField(default='HM1H6735', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='comments',
            field=models.CharField(default="Package won't be released for shipment until the shipment fees is being paid", max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='department_time',
            field=models.DateTimeField(auto_now=True, verbose_name='department time'),
        ),
        migrations.AddField(
            model_name='package',
            name='expected_delivery_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_mode',
            field=models.CharField(default='CASH', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='pick_up_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='package',
            name='pick_up_time',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(default='pending', max_length=7),
        ),
        migrations.AddField(
            model_name='package',
            name='type_of_shipment',
            field=models.CharField(default='Air Freight', max_length=50),
        ),
        migrations.AddField(
            model_name='receiver',
            name='country_code',
            field=models.CharField(default='+', max_length=4),
        ),
        migrations.AddField(
            model_name='sender',
            name='country_code',
            field=models.CharField(default='+', max_length=4),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageId',
            field=models.IntegerField(default=6812),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(default='DEST178877639635626-CARGO', max_length=25),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='phone',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='sender',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sender',
            name='phone',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
