# Generated by Django 3.2.4 on 2021-06-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipper', '0003_auto_20210604_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='department_time',
        ),
        migrations.AddField(
            model_name='package',
            name='departure_time',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='carrier_reference_no',
            field=models.CharField(default='HM1H2070', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageId',
            field=models.IntegerField(default=7033),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(default='DEST817877405945688-CARGO', max_length=25),
        ),
    ]
