# Generated by Django 3.2.4 on 2021-06-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipper', '0004_auto_20210604_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='carrier_reference_no',
            field=models.CharField(default='HM1H4661', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='departure_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageId',
            field=models.IntegerField(default=1214),
        ),
        migrations.AlterField(
            model_name='package',
            name='pick_up_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(default='DEST667487424861989-CARGO', max_length=25),
        ),
    ]
