# Generated by Django 3.2.4 on 2021-06-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipper', '0006_auto_20210604_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='carrier_reference_no',
            field=models.CharField(default='HM1H3759', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageId',
            field=models.IntegerField(default=8850),
        ),
        migrations.AlterField(
            model_name='package',
            name='toal_actual_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_volume_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(default='DEST642865480721799-CARGO', max_length=25),
        ),
    ]
