# Generated by Django 3.2.4 on 2021-06-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipper', '0008_auto_20210604_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='carrier_reference_no',
            field=models.CharField(default='HM1H2610', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageId',
            field=models.IntegerField(default=6203),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(default='DEST335498174583674-CARGO', max_length=25),
        ),
    ]
