# Generated by Django 3.2.4 on 2021-06-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipper', '0009_auto_20210604_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='toal_actual_weight',
            new_name='total_actual_weight',
        ),
        migrations.AlterField(
            model_name='package',
            name='carrier_reference_no',
            field=models.CharField(default='HM1H3817', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageId',
            field=models.IntegerField(default=8459),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(default='DEST120954737850488-CARGO', max_length=25),
        ),
    ]
