# Generated by Django 3.2.4 on 2021-06-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipper', '0010_auto_20210611_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='package',
            name='carrier_reference_no',
            field=models.CharField(default='HM1H3727', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageId',
            field=models.IntegerField(default=4214),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(default='DEST550501872899478-CARGO', max_length=25),
        ),
    ]
